[build]
builder = "nixpacks"
buildCommand = "chmod +x ./mvnw && ./mvnw clean package -DskipTests -Dmaven.repo.local=/app/.m2/repository"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
startTimeout = 180

[deploy.variables]
SPRING_PROFILES_ACTIVE = "production"
ADMIN_PASSWORD = "admin"