[build]
builder = "nixpacks"
buildCommand = "chmod +x ./mvnw && ./mvnw clean package -DskipTests -Dmaven.repo.local=/app/.m2/repository"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/actuator/health/liveness"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
startTimeout = 300

[deploy.variables]
SPRING_PROFILES_ACTIVE = "production"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin"
CHATBOT_ENABLED = "false"